name: anime_fitness_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.1
  go_router: ^14.8.1
  shared_preferences: ^2.0.13
  audioplayers: ^6.1.0
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1
  custom_lint: ^0.7.3
  riverpod_lint: ^2.6.4
  build_runner: ^2.4.15
  riverpod_generator: ^2.6.4

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: steel
      fonts:
        - asset: assets/steel.ttf
    - family: awaken
      fonts:
        - asset: assets/awaken.ttf